### ISSUE TITLE
Multiple code: is not configured correctly

### ISSUE THREAD

**Issue by bardware** [cflint/CFLint#228]
Today I happend to checkout the latest CFLint sources and buolt them with mvn.
I executed a command line from my history and got errors like:

```
Message code: VAR_HAS_PREFIX_OR_POSTFIX is not configured correctly.
Message code: VAR_INVALID_NAME is not configured correctly.
Message code: VAR_IS_TEMPORARY is not configured correctly.
Message code: VAR_ALLCAPS_NAME is not configured correctly.
Message code: VAR_TOO_LONG is not configured correctly.
Message code: VAR_TOO_SHORT is not configured correctly.
Message code: VAR_TOO_WORDY is not configured correctly.
Message code: SCOPE_ALLCAPS_NAME is not configured correctly.

Is there something I can do?

**Comment by ryaneberly** [comment]
Thanks. I noticed that on one of our systems as well.  I'm not sure what
changed that.  I will look.

**Comment by ryaneberly** [comment]
I'm having trouble isolating it.   How are you are invoking CFLint when it
happens?  Do you have an example of a minimal source file that demonstrates
the issue?

**Comment by bardware** [comment]
My command contains a list of many rules.

```
java -jar CFLint-0.11.0-all.jar -folder source/ -json -jsonfile source.json -verbose -includeRule ARG_DEFAULT_MISSING,NO_DEFAULT_INSIDE_SWITCH,GLOBAL_VAR,QUERYPARAM_REQ,CFQUERYPARAM_REQ,QUERYNEW_DATATYPE,AVOID_USING_CFDUMP_TAG,AVOID_USING_CFEXECUTE_TAG,AVOID_USING_CFINSERT_TAG,AVOID_USING_CFMODULE_TAG,AVOID_USING_CFUPDATE_TAG,AVOID_USING_CFINCLUDE_TAG,COMPONENT_HINT_MISSING,ARG_TYPE_MISSING,EXCESSIVE_FUNCTION_LENGTH,EXCESSIVE_COMPONENT_LENGTH,FUNCTION_TYPE_MISSING,EXCESSIVE_ARGUMENTS,EXCESSIVE_FUNCTIONS,FUNCTION_TOO_COMPLEX,AVOID_USING_ISDEBUGMODE,COMPLEX_BOOLEAN_CHECK,AVOID_USING_DEBUG_ATTR,COMPARE_INSTEAD_OF_ASSIGN,ARG_VAR_CONFLICT,NESTED_CFOUTPUT,MISSING_VAR,ARG_VAR_MIXED,OUTPUT_ATTR,AVOID_USING_CFABORT_TAG,AVOID_USING_ABORT,FUNCTION_HINT_MISSING,ARG_HINT_MISSING,ARG_TYPE_ANY,FUNCTION_TYPE_ANY,AVOID_USING_WRITEDUMP,AVOID_USING_STRUCTNEW,AVOID_USING_ARRAYNEW,EXPLICIT_BOOLEAN_CHECK,VAR_INVALID_NAME,VAR_ALLCAPS_NAME,VAR_TOO_SHORT,VAR_TOO_LONG,VAR_TOO_WORDY,VAR_IS_TEMPORARY,VAR_HAS_PREFIX_OR_POSTFIX,ARGUMENT_INVALID_NAME,ARGUMENT_ALLCAPS_NAME,ARGUMENT_TOO_SHORT,ARGUMENT_TOO_LONG,ARGUMENT_TOO_WORDY,ARGUMENT_IS_TEMPORARY,ARGUMENT_HAS_PREFIX_OR_POSTFIX,METHOD_INVALID_NAME,METHOD_ALLCAPS_NAME,METHOD_TOO_SHORT,METHOD_TOO_LONG,METHOD_TOO_WORDY,METHOD_IS_TEMPORARY,METHOD_HAS_PREFIX_OR_POSTFIX,COMPONENT_INVALID_NAME,COMPONENT_ALLCAPS_NAME,COMPONENT_TOO_SHORT,COMPONENT_TOO_LONG,COMPONENT_TOO_WORDY,COMPONENT_IS_TEMPORARY,COMPONENT_HAS_PREFIX_OR_POSTFIX,FILE_SHOULD_START_WITH_LOWERCASE,AVOID_USING_CREATEOBJECT,UNUSED_LOCAL_VARIABLE,UNUSED_METHOD_ARGUMENT >source.log 2>source.err

**Comment by bardware** [comment]
I noted the logs, when I played around with ignoring rules on component level. I took your own test file `src\test\resources\com\cflint\tests\Ignores\ignoreCFMLComponent2.cfc` 
This logs `Message code: VAR_IS_TEMPORARY is not configured correctly.`

**Comment by ryaneberly** [comment]
I see it too.  Thanks!

**Comment by ryaneberly** [comment]
I released cflint 0.11.1 to get this fix out.  Thanks for reporting it.

**Comment by mpaluchowski** [comment]
No, it's still not fixed :( Here's a bit of code that triggers the log message `Message code: VAR_INVALID_NAME is not configured correctly.`:

```coldfusion
component {
  public string function getStringFromStruct(required struct LocalData, required string keyToCheck) {
    if(!isNull(LocalData)) {
      if(StructKeyExists(LocalData, keyToCheck)) {
        return LocalData[keyToCheck];
      }
    }
    return '';
  }
}
```

and then the relevant position in the report (see attached TXT file) is missing a proper description in the "Message" line -- it just says `Message:VAR_INVALID_NAME`. _However_, when I change the variable name `LocalData` to `localData`, so that it starters with a lowercase letter, then the errors are gone completely.

The command I'm running for this one is simply:

```shell
java -jar CFLint-0.11.1-all.jar -file test.cfc
```
[cflint-result.txt](https://github.com/cflint/CFLint/files/680723/cflint-result.txt)

**Comment by ryaneberly** [comment]
"localData" with a lower "L" does not flag the same naming convention rule that "LocalData" does.
