### ISSUE TITLE
Parse error when multiple spaces in CFML tag

### ISSUE THREAD

**Issue by mpaluchowski** [cflint/CFLint#243]
The following code will produce a `PARSE_ERROR` at line 3:

```coldfusion
<cfcomponent>
  <cffunction name="foo" access="public" output="false" returntype="any">
    <cfreturn  >
  </cffunction>
</cfcomponent>
```

because of the double space in `<cfreturn  >`. There's no error when the tag contains either a single space `<cfreturn >` or no space before the closing `>`.

**Comment by ryaneberly** [comment]
fixed in cfparser develop branch.

**Comment by mpaluchowski** [comment]
Looks like this issue is still present in CFLint at 1c3c2d5. It wasn't yet merged into the cfparser version that's included in this CFLint build?

**Comment by ryaneberly** [comment]
You are right.  Sorry.  It is included in cfparser 2.4.3 now

**Comment by mpaluchowski** [comment]
This one just came back -- the code above again causes a `PARSE_ERROR` when there's more than a single space in the end of a tag.

**Comment by ryaneberly** [comment]
On 
`<cfreturn  >`
or something else?

The cfreturn test is still passing in cfparser.

**Comment by mpaluchowski** [comment]
The command I'm running is simply:

```shell
java -jar CFLint-1.2.0-SNAPSHOT-all.jar -xml -file .\test.cfc
```

(built from latest CFLint dev `24538ba12f38`, and the file I'm testing on is:

```
<cfcomponent>
  <cffunction name="foo">
    <cfreturn  >
  </cffunction>
</cfcomponent>
```

The errors are the same whether there's a `<cfreturn  >` or `<cfreturn  />` -- it's the double space that matters. The error is specifically, in the XML:

```xml
<issue severity="ERROR" id="PARSE_ERROR" message="PARSE_ERROR" category="CFLint" abbrev="PE">
  <location file="C:\Inbox\cflint-test\.\test.cfc" fileName="test.cfc" function="" column="0" line="3" message="Unable to parse" variable="&lt;EOF&gt;">
    <Expression><![CDATA[<cfreturn  >]]></Expression>
  </location>
</issue>
```

and in the console:

```shell
line 1:1 mismatched input '<EOF>' expecting {BOOLEAN_LITERAL, OPEN_STRING, CONTAINS, CONTAIN, GT, GTE, LTE, LT, EQ, NEQ, OR, TO, IMP, EQV, XOR, AND, NOT, MOD, VAR, NEW, FUNCTION, DEFAULT, '.', '+', '++', '-', '--', '!!', '!', '[', '(', '{', INCLUDE, ABORT, ADMIN, THROW, RETHROW, EXIT, PARAM, PROPERTY, LOCK, THREAD, TRANSACTION, SAVECONTENT, HTTP, CFHTTP, FILE, DIRECTORY, LOOP, SETTING, QUERY, STRING, NUMERIC, BOOLEAN, ANY, ARRAY, STRUCT, PRIVATE, PUBLIC, REMOTE, PACKAGE, REQUIRED, COMPONENT, LOG, APPLET, ASSOCIATE, AUTHENTICATE, CACHE, COL, COLLECTION, CONTENT, COOKIE, ERROR, EXECUTE, FORM, FTP, GRID, GRIDCOLUMN, GRIDROW, GRIDUPDATE, HEADER, HTMLHEAD, HTTPPARAM, CFHTTPPARAM, IMPERSONATE, INDEX, INPUT, INSERT, LDAP, LOCATION, MAIL, MAILPARAM, MODULE, OBJECT, OUTPUT, POP, PROCESSINGDIRECTIVE, PROCPARAM, PROCRESULT, QUERYPARAM, REGISTRY, REPORT, SCHEDULE, SCRIPT, SEARCH, SELECT, SERVLET, SERVLETPARAM, SET, SILENT, SLIDER, STOREDPROC, TABLE, TEXTINPUT, TREE, TREEITEM, UPDATE, WDDX, ZIP, CFCUSTOM_IDENTIFIER, IDENTIFIER, INTEGER_LITERAL, '#', FLOATING_POINT_LITERAL}
```

**Comment by ryaneberly** [comment]
@mpaluchowski , I see it now. Thanks!  It is fixed.
